apiVersion: v2
name: vault-certs
description: A Helm chart for deploying HashiCorp Vault leveraging certificates issued by Cert-Manager
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
- name: vault
  alias: base
  #version: 0.23.0
  version: 0.19.0
  repository: "https://helm.releases.hashicorp.com"
